# DataScience - 1 - numpy & pandas

Array Unidimensional

In [ ]:
import numpy as np
import pandas as pd

array_unidimensional = np.array([1, 2, 3, 4, 5,6])
print(array_unidimensional)

[1 2 3 4 5 6]


Array Bidimensional

In [ ]:
array_bidimensional = np.array([[1, 2, 3], [4, 5, 6]])
print(array_bidimensional)

[[1 2 3]
 [4 5 6]]


Array Multidimensional

In [ ]:
array_Multidimensional = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(array_Multidimensional)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Arrays de nros por default: np.zeros(5), np.ones(5), etc... otra opcion e hace lo mismo es: np.full(5,8)

In [ ]:
array_ceros = np.zeros(5)
print(array_ceros)

array_one = np.ones(5)
print(array_one)

array_full = np.full(5, 8)
print(array_full)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[8 8 8 8 8]


Array con secuencia de numeros

In [ ]:
#Generar un Rango de 20 Numeros
array = np.arange(20)
print(array)

#Generar un rango hasta el valor 10 de 2 en 2
array_rango = np.arange(0, 11, 2)
print(array_rango)

#Generar un rango hasta el valor 11 de 2 en 2 impar
array_rango = np.arange(1, 12, 2)
print(array_rango)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10]
[ 1  3  5  7  9 11]


Pandas - Dataframes

In [ ]:
# Pandas series es un array con indice
Numeros = range(50, 70, 2)
Numeros_serie = pd.Series(Numeros)
print(Numeros_serie)

print(Numeros_serie[2])

0    50
1    52
2    54
3    56
4    58
5    60
6    62
7    64
8    66
9    68
dtype: int64
54


In [ ]:
Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_64,

Ajedrez_df = pd.DataFrame(
Ajedrez_64,
columns=range(1,9),
index=['A','B','C','D','E','F','G','H'])
Ajedrez_df

1   2   3   4   5   6   7   8
A   1   2   3   4   5   6   7   8
B   9  10  11  12  13  14  15  16
C  17  18  19  20  21  22  23  24
D  25  26  27  28  29  30  31  32
E  33  34  35  36  37  38  39  40
F  41  42  43  44  45  46  47  48
G  49  50  51  52  53  54  55  56
H  57  58  59  60  61  62  63  64

Dataframe - indexación

In [ ]:
#busca un unico dato desde el indice y la columna
Ajedrez_df.iloc[1,6]


np.int64(15)

In [ ]:
#busqueda de datos recorriendo indice por indice
Ajedrez_df.iloc[2:5]   #traeme desde el indice 2 al 5, las columnas

1   2   3   4   5   6   7   8
C  17  18  19  20  21  22  23  24
D  25  26  27  28  29  30  31  32
E  33  34  35  36  37  38  39  40

In [ ]:
#Busca por indice y diferencia por columnas
Ajedrez_df.loc['B':'F', [1,4,7]]  #traeme desde los indices B al F, las columnas 1,4 y 7

1   4   7
B   9  12  15
C  17  20  23
D  25  28  31
E  33  36  39
F  41  44  47

Armado de Datasets

In [ ]:
datos = {
    'Nombre': ['   Juan  ', 'María  ', '   Pedro', ' Ana  '],
    'Edad': [25, 30, 35, 40],
    'Correo': ['juan@example.com','Maria@sample.com', 'pedro@demo.com', 'ana@testing.com'],
    'Ciudad': ['Madrid', 'Barc.', 'Valencia', 'Sevilla']
}

dataframe = pd.DataFrame(datos)
print(dataframe)


      Nombre  Edad            Correo    Ciudad
0     Juan      25  juan@example.com    Madrid
1    María      30  Maria@sample.com     Barc.
2      Pedro    35    pedro@demo.com  Valencia
3      Ana      40   ana@testing.com   Sevilla


Dataset - consulta de columna

In [ ]:
dataframe['Correo']

0    juan@example.com
1    Maria@sample.com
2      pedro@demo.com
3     ana@testing.com
Name: Correo, dtype: object

Dataset - crear una nueva columna

In [ ]:
dataframe['Pais'] = 'España'
dataframe

Nombre  Edad            Correo    Ciudad    Pais
0     Juan      25  juan@example.com    Madrid  España
1    María      30  Maria@sample.com     Barc.  España
2      Pedro    35    pedro@demo.com  Valencia  España
3      Ana      40   ana@testing.com   Sevilla  España

Dataset - manipulacion de datos (modificacion de los campos de la columna ciudad de minuscula a mayuscula)

In [ ]:
dataframe['Ciudad'] = dataframe['Ciudad'].str.upper()
dataframe

Nombre  Edad            Correo    Ciudad    Pais
0     Juan      25  juan@example.com    MADRID  España
1    María      30  Maria@sample.com     BARC.  España
2      Pedro    35    pedro@demo.com  VALENCIA  España
3      Ana      40   ana@testing.com   SEVILLA  España

Dataset - agregado de una columna y rellenarlo con datos de otra columna existente

Ejemplo 1: se crea la columna Dominio con los datos de la columna correo correspondiente al dominio

In [ ]:
dataframe['Dominio'] = dataframe['Correo'].str.split('@').str[1]
dataframe

Nombre  Edad            Correo    Ciudad    Pais      Dominio
0     Juan      25  juan@example.com    MADRID  España  example.com
1    María      30  Maria@sample.com     BARC.  España   sample.com
2      Pedro    35    pedro@demo.com  VALENCIA  España     demo.com
3      Ana      40   ana@testing.com   SEVILLA  España  testing.com

Ejemplo 2

In [ ]:
dataframe['Cod_ciudad'] = dataframe['Ciudad'].str[:3]
dataframe

Nombre  Edad            Correo    Ciudad    Pais      Dominio Cod_ciudad
0     Juan      25  juan@example.com    MADRID  España  example.com        MAD
1    María      30  Maria@sample.com     BARC.  España   sample.com        BAR
2      Pedro    35    pedro@demo.com  VALENCIA  España     demo.com        VAL
3      Ana      40   ana@testing.com   SEVILLA  España  testing.com        SEV

Dataset - deteccion de patrones de Texto

In [ ]:
filtrado = dataframe[dataframe['Correo'].str.contains('example')]
#print(filtrado)
filtrado

Nombre  Edad            Correo  Ciudad    Pais      Dominio Cod_ciudad
0     Juan      25  juan@example.com    True  España  example.com        MAD

Dataset - eliminación de espacios en blanco

In [ ]:
dataframe['Nombre'] = dataframe['Nombre'].str.strip()
print(dataframe)

  Nombre  Edad            Correo  Ciudad    Pais      Dominio Cod_ciudad
0   Juan    25  juan@example.com    True  España  example.com        MAD
1  María    30  Maria@sample.com   False  España   sample.com        BAR
2  Pedro    35    pedro@demo.com   False  España     demo.com        VAL
3    Ana    40   ana@testing.com   False  España  testing.com        SEV


Ojo! con el nombe Juan que tiene espacios adelante, si trabajo con Datasets no hay problema pero si hago print se toma en cuenta los espacios y para algunas busquedas asi que hay que usar el filtro de eliminacion de espacios en blanco